<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Report</title>
    <style>
        body {
            font-family: DejaVu Sans;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f8fafc;
        }
        .container {
            background-color: white;
            border-radius: 8px;
            padding: 30px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #e2e8f0;
        }
        .header h1 {
            color: #2563eb;
            margin: 0;
            font-size: 28px;
        }
        .header p {
            color: #64748b;
            margin: 5px 0 0 0;
            font-size: 16px;
        }
        .content {
            margin-bottom: 30px;
        }
        .report-info {
            background-color: #f1f5f9;
            padding: 20px;
            border-radius: 6px;
            margin: 20px 0;
        }
        .report-info h3 {
            color: #1e40af;
            margin: 0 0 10px 0;
            font-size: 18px;
        }
        .info-item {
            margin: 8px 0;
            display: flex;
            justify-content: space-between;
        }
        .info-label {
            font-weight: bold;
            color: #374151;
        }
        .info-value {
            color: #6b7280;
        }
        .footer {
            text-align: center;
            padding-top: 20px;
            border-top: 1px solid #e2e8f0;
            color: #9ca3af;
            font-size: 14px;
        }
        .button {
            display: inline-block;
            background-color: #2563eb;
            color: white;
            padding: 12px 24px;
            text-decoration: none;
            border-radius: 6px;
            font-weight: bold;
            margin: 10px 0;
        }
        .attachment-notice {
            background-color: #ecfdf5;
            border: 1px solid #10b981;
            color: #065f46;
            padding: 15px;
            border-radius: 6px;
            margin: 20px 0;
        }
        .attachment-notice strong {
            display: block;
            margin-bottom: 5px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📊 Your Report is Ready</h1>
            <p>eBooking CLAB System</p>
        </div>

        <div class="content">
            <p>Hello <strong>{{ $user->name }}</strong>,</p>
            
            <p>Your requested {{ $reportType }} report has been generated successfully and is attached to this email.</p>

            <div class="report-info">
                <h3>📋 Report Details</h3>
                <div class="info-item">
                    <span class="info-label">Report Type:</span>
                    <span class="info-value"> {{ $reportType }}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Format:</span>
                    <span class="info-value"> {{ strtoupper($report->report_format) }}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Records Count:</span>
                    <span class="info-value"> {{ number_format($report->record_count) }}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Generated On:</span>
                    <span class="info-value"> {{ $generatedAt }}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">File Name:</span>
                    <span class="info-value"> {{ $report->file_name }}</span>
                </div>
            </div>

            <div class="attachment-notice">
                <strong>📎 Attachment Information:</strong>
                The report file is attached to this email. Please check your attachments to download the {{ strtoupper($report->report_format) }} file.
            </div>

            <p>If you have any questions about this report or need additional information, please don't hesitate to contact the system administrator.</p>

            <p>Best regards,<br>
            <strong>eBooking CLAB System</strong></p>
        </div>

        <div class="footer">
            <p>This email was automatically generated by the eBooking CLAB System.<br>
            Please do not reply to this email.</p>
            <p>&copy; {{ date('Y') }} eBooking CLAB System. All rights reserved.</p>
        </div>
    </div>
</body>
</html>